main: com.rictacius.punishSystem.Main
version: 1.4.0
name: PunishSystem
depend: [Vault]

commands:
  punish:
    description: Main command
  warn:
    description: Warn command
  ban:
    description: Ban command
  psmodify:
    description: Modify command
  ipban:
    description: IPBan command
    aliases: [banip]
  pardon:
    description: Pardon a player